__all__ = (
    'HAND_PALM_CONNECTIONS_V1',
    'HAND_PALM_CONNECTIONS_V2',
    'HAND_THUMB_CONNECTIONS',
    'HAND_INDEX_FINGER_CONNECTIONS',
    'HAND_MIDDLE_FINGER_CONNECTIONS',
    'HAND_RING_FINGER_CONNECTIONS',
    'HAND_PINKY_FINGER_CONNECTIONS',
    'HAND_CONNECTIONS_V1',
    'HAND_CONNECTIONS_V2',
    'HAND_CONNECTIONS_STAR',
    'HAND_CONNECTIONS_CRYSTAL'
)

HAND_PALM_CONNECTIONS_V1 = ((0, 1), (0, 5), (9, 13), (13, 17), (5, 9), (0, 17))
HAND_PALM_CONNECTIONS_V2 = ((0, 1), (0, 5), (0, 9), (0, 13), (0, 17))
HAND_THUMB_CONNECTIONS = ((1, 2), (2, 3), (3, 4))
HAND_INDEX_FINGER_CONNECTIONS = ((5, 6), (6, 7), (7, 8))
HAND_MIDDLE_FINGER_CONNECTIONS = ((9, 10), (10, 11), (11, 12))
HAND_RING_FINGER_CONNECTIONS = ((13, 14), (14, 15), (15, 16))
HAND_PINKY_FINGER_CONNECTIONS = ((17, 18), (18, 19), (19, 20))

HAND_CONNECTIONS_V1 = frozenset().union(*[
    HAND_PALM_CONNECTIONS_V1, HAND_THUMB_CONNECTIONS,
    HAND_INDEX_FINGER_CONNECTIONS, HAND_MIDDLE_FINGER_CONNECTIONS,
    HAND_RING_FINGER_CONNECTIONS, HAND_PINKY_FINGER_CONNECTIONS
])
HAND_CONNECTIONS_V2 = frozenset().union(*[
    HAND_PALM_CONNECTIONS_V2, HAND_THUMB_CONNECTIONS,
    HAND_INDEX_FINGER_CONNECTIONS, HAND_MIDDLE_FINGER_CONNECTIONS,
    HAND_RING_FINGER_CONNECTIONS, HAND_PINKY_FINGER_CONNECTIONS
])

HAND_CONNECTIONS_STAR = ((4, 20), (20, 8), (8, 16), (16, 12), (12, 4))
HAND_CONNECTIONS_CRYSTAL = (
    (4, 8), (4, 12), (4, 16), (4, 20), (8, 12), (8, 16), (8, 20),
    (12, 16), (12, 20), (16, 20)
)
